src/web/forms/login.py
#! /usr/bin/env python
#-*- coding: utf-8 -*-

# ***** BEGIN LICENSE BLOCK *****
# This file is part of Shelter Database.
# Copyright (c) 2016 Luxembourg Institute of Science and Technology.
# All rights reserved.
#
#
#
# ***** END LICENSE BLOCK *****

__author__ = "Cedric Bonhomme"
__version__ = "$Revision: 0.1 $"
__date__ = "$Date: 2016/03/30 $"
__revision__ = "$Date: 2016/03/30 $"
__copyright__ = "Copyright 2016 Luxembourg Institute of Science and Technology"
__license__ = ""

from flask_wtf import Form
from flask import url_for, redirect
from wtforms import validators, TextField, PasswordField, \
                    SubmitField, HiddenField
from flask_wtf.html5 import EmailField

from web.models import User
from web.lib import utils

class RedirectForm(Form):
    """
    Secure back redirects with WTForms.
    """
    next = HiddenField()

    def __init__(self, *args, **kwargs):
        Form.__init__(self, *args, **kwargs)
        if not self.next.data:
            self.next.data = utils.get_redirect_target() or ''

    def redirect(self, endpoint='start', **values):
        if utils.is_safe_url(self.next.data):
            return redirect(self.next.data)
        target = utils.get_redirect_target()
        return redirect(target or url_for(endpoint, **values))

class LoginForm(RedirectForm):
    """
    Login form.
    """
    email = TextField("Email",
        [validators.Required("Please enter your email address.")])
    password = PasswordField('Password',
        [validators.Required("Please enter a password.")])
    submit = SubmitField("Log In")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        if not super(LoginForm, self).validate():
            return False

        user = User.query.filter(User.email==self.email.data).first()
        if user and user.check_password(self.password.data):
            self.user = user
            return True
        else:
            self.email.errors.append("Invalid name or password")
            return False

class SignupForm(RedirectForm):
    """
    Sign up form (registration).
    """
    name = TextField("Name",
            [validators.Required("Please enter your name.")])
    email = EmailField("Email",
            [validators.Length(min=6, max=35),
             validators.Required("Please enter your email address.")])
    password = PasswordField("Password",
            [validators.Required("Please enter a password."),
             validators.Length(min=6, max=100)])
    submit = SubmitField("Sign up")

    def validate(self):
        validated = super().validate()
        user = User.query.filter(User.email==self.email.data).first()
        if user:
            self.email.errors.append('Email already taken')
            validated = False
        return validated

src/web/forms/profile.py
#! /usr/bin/env python
#-*- coding: utf-8 -*-

# ***** BEGIN LICENSE BLOCK *****
# This file is part of Shelter Database.
# Copyright (c) 2016 Luxembourg Institute of Science and Technology.
# All rights reserved.
#
#
#
# ***** END LICENSE BLOCK *****

__author__ = "Cedric Bonhomme"
__version__ = "$Revision: 0.1 $"
__date__ = "$Date: 2016/06/06 $"
__revision__ = "$Date: 2016/06/06 $"
__copyright__ = "Copyright 2016 Luxembourg Institute of Science and Technology"
__license__ = ""

from flask_wtf import Form
from flask import url_for, redirect
from wtforms import validators, TextField, PasswordField, SelectField, \
                    SubmitField, HiddenField
from flask_wtf.html5 import EmailField
from sqlalchemy import distinct

from bootstrap import db
from web.models import User, Translation

class ProfileForm(Form):
    """
    Edit user own information.
    """
    name = TextField("Nickname",
            [validators.Required("Please enter your nickname.")])
    email = EmailField("Email",
               [validators.Length(min=6, max=35),
                validators.Required("Please enter your email.")])
    organization = TextField("Organization")
    # preferred_language = SelectField("Preferred language")
    password = PasswordField("Shelter-database password")
    password_conf = PasswordField("Shelter-database password confirmation")
    submit = SubmitField("Save")

    """
    def set_languages_choice(self):
        self.preferred_language.choices = [('en', 'en')]
        languages = [(language[0], language[0]) for language in \
                        db.session.query(distinct(Translation.language_code))]
        self.preferred_language.choices.extend(languages)
    """

    def validate(self):
        validated = super(ProfileForm, self).validate()
        if self.password.data != self.password_conf.data:
            message = "Passwords aren't the same."
            self.password.errors.append(message)
            self.password_conf.errors.append(message)
            validated = False
        if self.name.data != User.make_valid_name(self.name.data):
            self.name.errors.append('This nickname has '
                    'invalid characters. Please use letters, numbers, dots and'
                    ' underscores only.')
            validated = False
        return validated

src/web/views/shelter.py
#! /usr/bin/env python
#-*- coding: utf-8 -*-

# ***** BEGIN LICENSE BLOCK *****
# This file is part of Shelter Database.
# Copyright (c) 2016 Luxembourg Institute of Science and Technology.
# All rights reserved.
#
#
#
# ***** END LICENSE BLOCK *****

__author__ = "Cedric Bonhomme"
__version__ = "$Revision: 0.8 $"
__date__ = "$Date: 2016/05/31$"
__revision__ = "$Date: 2016/06/21 $"
__copyright__ = "Copyright 2016 Luxembourg Institute of Science and Technology"
__license__ = ""

import os
from werkzeug.utils import secure_filename
from flask import Blueprint, request, flash, render_template, current_app, \
                    url_for, redirect, make_response
from flask_login import login_required, current_user

from PIL import Image, ImageFile

import conf
import time
import logging
import logging.handlers
from bootstrap import db
from web.views.common import load_shelter_info
from web.lib.utils import redirect_url, allowed_file, create_thumbnail
from web.lib.misc_utils import create_pdf
from web.forms import LoginForm
from web.models import Shelter, Property, \
                        ShelterPicture, ShelterDocument, Section, Association, Value, User

shelter_bp = Blueprint('shelter_bp', __name__, url_prefix='/shelter')
shelters_bp = Blueprint('shelters', __name__, url_prefix='/shelters')

@shelter_bp.route('/<int:shelter_id>/<section_name>', methods=['GET'])
@shelter_bp.route('/<int:shelter_id>/<section_name>/<to_pdf>', methods=['GET'])
def details(shelter_id=0, section_name="", to_pdf=None):
    sections = Section.query.filter()
    try:
        shelter, section, categories, pictures, documents = \
                                load_shelter_info(shelter_id, section_name)
    except Exception as e:
        flash(str(e), "warning")
        return redirect(redirect_url())

    if to_pdf == "to_pdf":
        try:
            pdf_file = create_pdf(render_template('pdf/template1.html',
                                    shelter=shelter, section=section,
                                    categories=categories, pictures=pictures))
            response = make_response(pdf_file)
            response.headers['Content-Type'] = 'application/pdf'
            response.headers['Content-Disposition'] = \
                'attachment; filename=%s.pdf' % 'shelter'
            return response
        except Exception as e:
            print(e)
            flash('Error when generating PDF file.', 'danger')

    return render_template('details.html', shelter=shelter,
                        categories=categories, pictures=pictures,
                        sections=sections, section=section, documents=documents)


@shelter_bp.route('/edit/<int:shelter_id>/<section_name>', methods=['GET'])
@login_required
def edit(shelter_id=0, section_name=""):
    shelter = Shelter.query.filter(Shelter.id == shelter_id).first()

    if current_user.is_admin:
        pass
    elif shelter is not None and current_user.id == shelter.user_id:
        pass
    else:
        flash('Only Admin or shelter creater have edit permission',
              'warning')
        # render_template('errors/403.html'), 403
        return redirect(url_for('join'))

    user = User.query.filter(User.id == shelter.user_id).first()

    sections = Section.query.filter()
    try:
        shelter, section, categories, pictures, documents = \
                                load_shelter_info(shelter_id, section_name)
    except Exception as e:
        flash(str(e), "warning")
        return redirect(redirect_url())

    return render_template('edit.html', shelter=shelter, categories=categories,
                           pictures=pictures, sections=sections, section=section,
                           documents=documents, user=user)


@shelter_bp.route('/delete/<int:shelter_id>', methods=['GET'])
@login_required
def delete(shelter_id=0, section_name=""):
    """
    Delete a shelter. if created by requesting user
    """
    shelter = Shelter.query.filter(Shelter.id==shelter_id,
                                   Shelter.user_id==current_user.id)
    if shelter is not None:
        ShelterPicture.query.filter(ShelterPicture.shelter_id==shelter_id).delete()

        properties = Property.query.filter(Property.shelter_id==shelter_id)
        for property in properties:
            Association.query.filter(Association.property_id==property.id).delete()
            db.session.delete(property)

        shelter.delete()
        db.session.commit()

    return redirect(redirect_url())


@shelter_bp.route('/edit/<int:shelter_id>/<section_name>', methods=['POST'])
@login_required
def get_media(shelter_id=0, section_name=""):
    """
    Get the media (pictures or documents) for the shelter sent via a POST
    request.
    """
    shelter = Shelter.query.filter(Shelter.id==shelter_id).first()
    if not shelter:
        flash("No such shelter", "warning")
        return redirect(redirect_url())

    file = request.files.get('mediafile', None)
    if file and file.filename == '':
        flash('No selected file', 'warning')
        return redirect(request.url)
    if file and allowed_file(file.filename,
                                conf.ALLOWED_EXTENSIONS_PICTURE.union(
                                            conf.ALLOWED_EXTENSIONS_DOCUMENT)):
        if 'pictures' in request.form:
            path = os.path.join(conf.SHELTERS_PICTURES_SERVER_PATH, str(shelter.id))
        if 'documents' in request.form:
            path = os.path.join(conf.SHELTERS_DOCUMENTS_SERVER_PATH, str(shelter.id))
        if not os.path.exists(path):
            os.makedirs(path)
        filename = secure_filename(file.filename)
        file.save(os.path.join(path , filename))

        category_id = request.form['category_id']
		
        if category_id:
            if 'pictures' in request.form:
                new_media = ShelterPicture(file_name=filename,
                        shelter_id=shelter.id, category_id=category_id)
            if 'documents' in request.form:
                new_media = ShelterDocument(file_name=filename,
                        shelter_id=shelter.id, category_id=category_id)
            db.session.add(new_media)
            db.session.commit()

    return redirect(request.url)

@shelter_bp.route('/edit/multidocument/<int:shelter_id>/<category_id>/<section>', methods=['POST'])
@login_required
def get_multimedia_documents(shelter_id=0, category_id=2, section="Documents"):
    """
    Get the media (documents) for the shelter sent via a POST
    request.
    """
    shelter = Shelter.query.filter(Shelter.id==shelter_id).first()
    if not current_user.is_authenticated:
        return 'unauthorized', 403
	
    if not shelter:
        return 'no such shelter', 400 

    file = request.files.get('mediafile', None)

    for f in request.files:
        if request.files[f] and request.files[f].filename == '':
            return 'No selected file', 400 
        if request.files[f] and not allowed_file(request.files[f].filename,
                                conf.ALLOWED_EXTENSIONS_DOCUMENT):	
            return 'File type not allowed', 400
		
        path = os.path.join(conf.SHELTERS_DOCUMENTS_SERVER_PATH, str(shelter.id))
        logging.debug('path:' + path)
			
        if not os.path.exists(path):
            os.makedirs(path)

        filename = secure_filename(request.files[f].filename)
        request.files[f].save(os.path.join(path , filename))

        if category_id:
            new_media = ShelterDocument(file_name=filename,
               shelter_id=shelter.id, category_id=category_id)
            db.session.add(new_media)
            db.session.commit()
            return str(new_media.id), 200

    return 'Document not uploaded', 400
			
@shelter_bp.route('/edit/multi/<int:shelter_id>/<category_id>/<section>', methods=['POST'])
#@login_required
def get_multi_media(shelter_id=0, category_id=2, section = 'Identification'):
    """
    Get pictures for the shelter sent by Dropzone via a POST
    request.
    """
    first = True
    ImageFile.LOAD_TRUNCATED_IMAGES = True
    imgwidth = 1280
	
    shelter = Shelter.query.filter(Shelter.id==shelter_id).first()
    shelter_id_query = db.session.query(Value.name)\
        .join(Association,Property,Shelter)\
        .filter(Shelter.id==shelter_id, Property.attribute_id==1)\
        .first()
    
    shelter_id_attribute = shelter_id_query[0]
    
    if not shelter:
        return 'no such shelter', 400 

    for f in request.files:
        if request.files[f] and request.files[f].filename == '':
            return 'No selected file', 400 
        if request.files[f] and allowed_file(request.files[f].filename,
                                conf.ALLOWED_EXTENSIONS_PICTURE.union(
                                            conf.ALLOWED_EXTENSIONS_DOCUMENT)):								
            path = os.path.join(conf.SHELTERS_PICTURES_SERVER_PATH, str(shelter.id))
            logging.debug('path:' + path)
			
            if not os.path.exists(path):
                os.makedirs(path)

            file_extension = os.path.splitext(request.files[f].filename)[1]
            
            exist_main = db.session.query(ShelterPicture.is_main_picture).filter(ShelterPicture.is_main_picture==True,ShelterPicture.shelter_id==shelter.id).first()
            if not exist_main: 
            	filename = str(shelter_id_attribute) + '_' + section + "_" + "Facade" + file_extension
            	thumbname = str(shelter_id_attribute) + '_' + section + "_" + "Facade_thumbnail" + file_extension
            else:
            	filename = str(shelter_id_attribute) + '_' + section + "_" + str(time.time()) + file_extension

src/web/views/user.py
#! /usr/bin/env python
#-*- coding: utf-8 -*-

# ***** BEGIN LICENSE BLOCK *****
# This file is part of Shelter Database.
# Copyright (c) 2016 Luxembourg Institute of Science and Technology.
# All rights reserved.
#
#
#
# ***** END LICENSE BLOCK *****

__author__ = "Cedric Bonhomme"
__version__ = "$Revision: 0.1 $"
__date__ = "$Date: 2016/06/06$"
__revision__ = "$Date: 2016/06/06 $"
__copyright__ = "Copyright 2016 Luxembourg Institute of Science and Technology"
__license__ = ""

from flask import Blueprint, flash, render_template, url_for, request, redirect
from flask_login import login_required, current_user

from bootstrap import db
from web.models import User
from web.forms import ProfileForm
import conf

user_bp = Blueprint('user_bp', __name__, url_prefix='/user')

@user_bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    user = User.query.filter(User.id==current_user.id).first()
    form = ProfileForm()
    # form.set_languages_choice()

    if request.method == 'POST':
        if form.validate():
            # update user

            if form.password.data and \
                form.password.data == form.password_conf.data:
                user.set_password(form.password.data)

            form.populate_obj(user)
            db.session.commit()

            flash('User successfully updated', 'success')
            return redirect(url_for('user_bp.profile'))
        else:
            flash('User update failed', 'danger')
            return render_template(
                    'profile.html', user=user, form=form,
                    humanitarian_id_auth_uri=conf.HUMANITARIAN_ID_AUTH_URI,
                    humanitarian_id_app_uri=conf.HUMANITARIAN_ID_APP_URI)

    if request.method == 'GET':
        form = ProfileForm(obj=user)
        return render_template(
                'profile.html', user=user, form=form,
                humanitarian_id_auth_uri=conf.HUMANITARIAN_ID_AUTH_URI,
                humanitarian_id_app_uri=conf.HUMANITARIAN_ID_APP_URI)

@user_bp.route('/shelters', methods=['GET'])
@login_required
def shelters():
    user = User.query.filter(User.id==current_user.id).first()
    return render_template('shelters.html', shelters=user.shelters)

src/web/templates/details.html
{% extends "layout.html" %}
{% block head %}
    {{ super() }}
    <script src="{{ url_for('static', filename='lib/npm_components/lightbox2/dist/js/lightbox.min.js') }}"></script>
    <link href="{{ url_for('static', filename='lib/npm_components/lightbox2/dist/css/lightbox.css') }}" rel="stylesheet" media="screen" />
{% endblock %}
{% block content %}
<div class="container-fluid">
    <ul id="myTab" class="nav nav-tabs" role="tablist">
        {% for current_section in sections %}
            <li id="tab-{{ current_section.id }}" {% if current_section.id  == section.id  %}class="active"{% endif %}>
                <a href="{{ url_for('shelter_bp.details', shelter_id=shelter.id, section_name=current_section.name | replace(' ', '-')) }}">{{ current_section.name | translate }}</a>
            </li>
        {% endfor %}

        <li id="tab-edit" class="pull-right" >
            <a id="btn-edit" class="btn" style="font-weight: bold;"
            title="Edit"
            href="{{ url_for('shelter_bp.edit', shelter_id=shelter.id, section_name=section.name | replace(' ', '-')) }}">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </a>
        </li>

        <li id="tab-print" class="pull-right" >
            <a id="btn-print" class="btn" style="font-weight: bold;"
            title="Printer friendly version"
            href="{{ url_for('shelter_bp.details', shelter_id=shelter.id, section_name=section.name | replace(' ', '-'), to_pdf='to_pdf') }}">
                <span class="glyphicon glyphicon-print" aria-hidden="true"></span>
            </a>
        </li>
    </ul>

    {% for category in section.categories %}
        {% for sub_category in category.sub_categories %}
            {% if sub_category.name in categories  %}
                <fieldset id="{{ sub_category.id }}" class="border">
                    <legend class="border">
                        <span class="section-title">{{ sub_category.name | translate }}</span>
                    </legend>
                    <div class="col-md-8">
                        {% for property  in categories[sub_category.name] %}
                            <div class="row">
                                <div class="col-md-4">
                                    <p><b {% if property.attribute.pictures.count() != 0 %}style="border-bottom: 1px dotted #000000; cursor:pointer;" attrId="{{ property.attribute.id }}" class="attribute-multimedia-asset"{% endif %}>{{ property.attribute.name | translate }}</b></p>
                                </div>
                                <div class="col-md-4">
                                    <p>
                                        {% if property.attribute.type == 'yes / no' %}
                                            {% if property.values[0].name in ("1","on") %}Yes{% else %}No{% endif %}
                                        {% else %}
                                            {% for value in property.values[:-1] %}
                                                {{ value.name | translate }},&nbsp;
                                            {% endfor %}
                                            {{ property.values[-1].name | translate }}
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="col-md-4">
                        <div class="row">
                            {% for picture in pictures[sub_category.name] %}
                                <div class="col-md-1 thumbShelterPicture">
                                    <a href="/public/pictures/shelters/{{ shelter.id }}/{{ picture.file_name }}" data-lightbox="{{ category }}">
                                        <img src="/public/pictures/shelters/{{ shelter.id }}/{{ picture.file_name }}" style="padding-top:3px;" />
                                    </a>
                                </div>
                            {% endfor %}
                        </div>

                        {% if sub_category.name == "Documents"  %}
                            <div class="row">
                                {% for document in documents[sub_category.name] %}
                                    <div>
                                        <a href="/public/documents/shelters/{{ shelter.id }}/{{ document.file_name }}" download>
                                            <span class="glyphicon glyphicon-file" title="{{ document.file_name }}"></span>&nbsp;{{ document.file_name }}
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </fieldset>
            {% endif %}
        {% endfor %}
    {% endfor %}
</div><!-- /.container -->

<div class="modal fade bs-example-modal-lg" id="infoDialog" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel"><span id="infoDialogTitle"></span></h4>
            </div>
            <div class="modal-body">
                <div align="center" id="listOfPictures"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" class="source">
$(document).ready(function() {
    $( ".attribute-multimedia-asset" ).click(show_multimedia_assets);
});

function retrieve_and_display_multimedia_asset(attributeId) {
    var filters = [{"name":"id","op":"eq","val":attributeId}];
    $.ajax({
        type: 'GET',
        url: '/api/attribute',
        contentType: "application/json",
        dataType: "json",
        data: {"q": JSON.stringify({"filters": filters})},
        success: function(result) {
            $('#listOfPictures').empty();
            result.objects[0].pictures.map(function(picture) {
                oImg = document.createElement("img");
                oImg.setAttribute('src', '/public/pictures/attributes/en/' + picture.file_name );
                oImg.setAttribute('alt', picture.file_name);
                oImg.setAttribute('title', picture.file_name);
                oImg.setAttribute('height', '600px');
                oImg.setAttribute('width', '600px');
                $('#listOfPictures').append(oImg);
                $('#listOfPictures').append(document.createElement("hr"));
            })
            $('#listOfPictures hr:last-child').remove();
            $('#infoDialog').modal({backdrop:'static', keyboard:false});
        },
        error: function(XMLHttpRequest, textStatus, errorThrown){
            //document.getElementById("geolocation").innerHTML = XMLHttpRequest.responseText;
        }
        }); // ajax closed
}

function show_multimedia_assets(evt) {
    evt = evt || window.event; // The event that was fired
    var targ = evt.target || evt.srcElement; // the element that was clicked
    var el = this; // the element that fired the event

    $('#infoDialogTitle').text("Description");
    var attrId = $(el).attr('attrId');

    retrieve_and_display_multimedia_asset(attrId);

}
</script>
{% endblock %}

src/web/templates/help_pages.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h1 class="page-title">{{ page.name }}</h1>
     {{ page.content | safe }}
</div>
{% endblock %}

src/web/templates/humanitarianid_login.html
{% extends "layout.html" %}

{% block content %}
<h3>Please Wait.....</h3>
{% endblock %}
{% block defer_extra %}
<script>
    $(document).ready(function() {
        if (window.location.hash.indexOf('access_token=') >= 0) {
            window.location.href = '' + '?' + window.location.hash.substr(1);
        }
    });
</script>
{% endblock %}

src/web/templates/knowledgebase.html
{% extends "layout.html" %}
{% block content %}
        <section class="contribute">
                <div class="content">
                    <h1>Knowledge base</h1>
                    <p>As open Shelter Database we share knowledge</p>
                </div>
            </section>
            <section class="knowledge background" style="background-image: url('{{ url_for('static', filename='img/2.jpg') }}')">
                <div class="overlay"></div>
                <div class="toplayer">
                    <h3>Choose your Section</h3>

                    <div class="flexbox">
                        <div class="box">
                            <a href="page/Bibliography">
                                <i class="head_no_color fa icon-book fa-inverse"></i>
                                <h4>Bibliography</h4>
                            </a>
                        </div>
                        <div class="box">
                            <a href="page/Glossary">
                                <i class="head_no_color fa icon-list-bullet fa-inverse"></i>
                                <h4>Glossary</h4>
                            </a>
                        </div>
                        <div class="box">
                            <a href="page/Recommendations">
                                <i class="head_no_color fa icon-thumbs-up fa-inverse"></i>
                                <h4>Recommendations</h4>
                            </a>
                        </div>
                    </div>

                </div>
            </section>
{% endblock %}

src/web/templates/shelters.html
{% extends "layout.html" %}

{% block assets_start %}
    {{ super() }}
	<link rel="stylesheet" type="text/css" href='{{ url_for("static", filename="css/bootstrap_custom.css") }}' media="screen, print">
{% endblock %}

{% block content %}
<div class="container">
    <h1>Shelters</h1>
    <table id="allshelters" class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>ID</th>
                <th>Name</th>
                <th>Zone</th>
                <th>Created at</th>
				<th>Action</th>
            </tr>
        </thead>
        <tbody>
        {% for shelter in shelters %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ shelter.get_values_of_attribute(attribute_name='ID')[0].name }}</td>
                <td><a href="{{ url_for('shelter', shelter_id=shelter.id) }}">{{ shelter.get_values_of_attribute(attribute_name='Name of shelter')[0].name }}</a></td>
                <td>{{ shelter.get_values_of_attribute(attribute_name='Zone')[0].name }}</td>
                <td>{{ shelter.created_at }}</td>
				<td><a href="{{ url_for('shelter_bp.edit', shelter_id=shelter.id, section_name='General-Information' | replace(' ', '-')) }}">
                        <i class="glyphicon glyphicon-edit"></i>
                    </a>
                    <a class="delete-shelter-btn" href="{{ url_for('shelter_bp.delete', shelter_id=shelter.id, next='/user/shelters') }}">
                        <i class="glyphicon glyphicon-remove" title="Delete this shelter"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block defer %}

		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js"></script>
		
		<script>
			$(document).ready(function() {
                $('.delete-shelter-btn').click(function(event){
                    if(!confirm('You are going to delete this shelter.')){
                        event.preventDefault();
                    }
                });

				$('#allshelters').DataTable({
						"bStateSave": true, // on sauvegarde l'état dans un cookie
						"aaSorting": [[2, "asc" ]], // on trie par défaut sur la colonne "Name"
						"bJQueryUI": false,
						"bInfo": false,
						"aoColumnDefs": [
											{
												"bSortable": false, "aTargets": [ 0 ]
											}
										],
					   "aoColumns": [
									null,
									{ "sSortDataType": "dom-checkbox" },
									{ "sSortDataType": "dom-checkbox" },
									{ "sSortDataType": "dom-checkbox" },
									{ "sSortDataType": "dom-checkbox" }
									]
					});
            });
			</script>
{% endblock %}